// Types para guardar blog en API
const AGREGAR_BLOG = 'AGREGAR_BLOG';
const AGREGAR_BLOG_EXITO = 'AGREGAR_BLOG_EXITO';
const AGREGAR_BLOG_ERROR = 'AGREGAR_BLOG_ERROR';
// Resetear state del blog
const RESET = 'RESET';
// Types para listar blogs desde la petición de la API
const COMENZAR_DESCARGA_BLOGS = 'COMENZAR_DESCARGA_BLOGS';
const DESCARGA_BLOGS_EXITO = 'DESCARGA_BLOGS_EXITO';
const DESCARGA_BLOGS_ERROR = 'DESCARGA_BLOGS_ERROR';
// Types para eliminar blog
const OBTENER_BLOG_ELIMINAR = 'OBTENER_BLOG_ELIMINAR';
const BLOG_ELIMINADO_EXITO = 'BLOG_ELIMINADO_EXITO';
const BLOG_ELIMINADO_ERROR = 'BLOG_ELIMINADO_ERROR';
// Obtener datos de blog a partir de un id
const OBTENEER_BLOG = 'OBTENEER_BLOG';
const OBTENEER_BLOG_EXITO = 'OBTENEER_BLOG_EXITO';
const OBTENEER_BLOG_ERROR = 'OBTENEER_BLOG_ERROR';
// Types para actualizar blog
const UPDATE_BLOG = 'UPDATE_BLOG';
const UPDATE_BLOG_EXITO = 'UPDATE_BLOG_EXITO';
const UPDATE_BLOG_ERROR = 'UPDATE_BLOG_ERROR';
// Exportar variables
export {
  AGREGAR_BLOG,
  AGREGAR_BLOG_EXITO,
  AGREGAR_BLOG_ERROR,
  RESET,
  COMENZAR_DESCARGA_BLOGS,
  DESCARGA_BLOGS_ERROR,
  DESCARGA_BLOGS_EXITO,
  BLOG_ELIMINADO_ERROR,
  BLOG_ELIMINADO_EXITO,
  OBTENER_BLOG_ELIMINAR,
  OBTENEER_BLOG,
  OBTENEER_BLOG_ERROR,
  OBTENEER_BLOG_EXITO,
  UPDATE_BLOG,
  UPDATE_BLOG_ERROR,
  UPDATE_BLOG_EXITO,
};
